name: TravelApp - backend

services:
  express:
    build: 
      context: .
    container_name: travel-express
    environment:
      MONGO_URL_PROD: mongodb://mongodb:27017/travelApp-project-backend
      IS_DOCKER: true
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    healthcheck:
      test: ["CMD", "wget", "-q0-", "http://localhost:3000/health"] 
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 15s
    
  mongodb:
    image: mongo
    container_name: travel-mongo
    restart: always
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local