name: travelApp-project-backend

on: 
  push:
    branches:
      - release
      - deployment
    tags: 
      - 'v*'  
  pull_request:
    branches:
      - release
      - deployment

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: travelapp-backend
  IS_CI: true
  OWNER_LC: ""
  REPO_LC: ""
  AWS_REGION: ap-southeast-2                     
  ECR_REPOSITORY: travelapp-backend               
  ECS_SERVICE: travelapp-task-service-m5fybvnr    
  ECS_CLUSTER: able-flamingo-sp803j                 
  ECS_TASK_DEFINITION: arn:aws:ecs:ap-southeast-2:304619557163:task-definition/travelapp-task:3           
                                              # set this to the path to your Amazon ECS task definition
                                              # file, e.g. .aws/task-definition.json
  ECS_CONTAINER_NAME: 304619557163.dkr.ecr.ap-southeast-2.amazonaws.com/travel-backend
                                             
permissions:
  contents: write
  packages: write

jobs:
  build-and-verify:
    runs-on: ubuntu-latest
    environment: prod

    services:
      mongo: 
        image: mongo:6
        ports:
          - 27017:27017

    steps:
      # ------------ GIT + NODE ------------ 
      - name: Checkout repository
        uses: actions/checkout@v4
        with: 
            fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v6
        with: 
          node-version: 24

      - name: Install dependencies
        run: npm ci
      
      # ------------ TESTING ------------ 
      - name: Run tests
        run: npm test

      - name: Creating blank .env file
        run: touch .env  
      
      # ------------ DOCKER COMPOSE TEST PHASE ------------ 

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3  

      - name: Build and start services for verification
        run:  docker compose -f Docker-compose.yaml up -d --build

      - name: Stop Docker services after verification
        run: docker compose -f Docker-compose.yaml down
      
  tag-and-publish:
    needs: build-and-verify
    runs-on: ubuntu-latest
    environment: prod
    outputs:
      image_tag: ${{ steps.tag_version.outputs.new_tag }}
      image_name: ghcr.io/${{ env.REPO_LC }}/travelapp-backend:${{ steps.tag_version.outputs.new_tag }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with: 
            fetch-depth: 0

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3  

      # ------------ LOWERCASE FOR DOCKER TAGS ------------ 
      - name: Set lowercase repository name
        run: |
          echo "OWNER_LC=${OWNER,,}" >> $GITHUB_ENV
          echo "REPO_LC=${REPO,,}" >> $GITHUB_ENV
        env:
          OWNER: '${{ github.repository_owner }}'
          REPO: '${{ github.repository }}'

      # ------------ LOGIN TO GHCR ------------ 
      - name: Login to Docker Hub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN}}

      # ------------ VERSION TAGGING ------------ 
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: "travelApp-v"
          release_branches: release
          default_bump: patch
          dry_run: false

      # ------------ BUILDX PRODUCTION IMAGE ------------ 
      - name: Build and push production image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            ghcr.io/${{ env.REPO_LC }}/travelapp-backend:latest
            ghcr.io/${{ env.REPO_LC }}/travelapp-backend:${{ steps.tag_version.outputs.new_tag }}

      # ------------ CREATE GITHUB RELEASE ------------ 
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
      
  #deploy:
  # needs: tag-and-publish
  # runs-on: ubuntu-latest
  # environment: prod

  #  steps:
  #    - name: Deploy to Render
  #      run: curl -f ${{ secrets.RENDER_DEPLOY_HOOK }}
          

  deploy:
    name: Deploy to Amazon ECS
    runs-on: ubuntu-latest
    needs: tag-and-publish
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }} 

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Login to Docker Hub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN}}

      - name: Pull image from GHCR
        run: |
          docker pull ghcr.io/${{ env.REPO_LC }}/travelapp-backend:${{ needs.tag-and-publish.outputs.image_tag }}"

      - name: Tag image for ECR
        run: |
          docker tag \ 
          ghcr.io/${{ env.REPO_LC }}/travelapp-backend:${{ needs.tag-and-publish.outputs.image_tag }} \
          ${{ steps.login-ecr.outputs.registry }}/travel-backend:${{ needs.tag-and-publish.outputs.image_tag }}

      - name: Push image to ECR
        run: |
          docker push \ 
          ${{ steps.login-ecr.outputs.registry }}/travel-backend:${{ needs.tag-and-publish.outputs.image_tag }}

      - name: Render ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: .github/ecs/task-definition.json
          container-name: ${{ env.ECS_CONTAINER_NAME }}
          image: ${{ steps.login-ecr.outputs.registry }}/travel-backend:${{ needs.tag-and-publish.outputs.image_tag }}

      - name: Deploy to ECS 
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
        