name: CI/CD pipeline

on: 
  push:
    branches:
      - release
      - deployment
    tags: 
      - 'v*'  
  pull_request:
    branches:
      - release
      - deployment

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: travelapp-backend
  IS_CI: true
  OWNER_LC: ""
  REPO_LC: ""
  AWS_REGION: ap-southeast-2                                   
  ECS_SERVICE: travelapp-task-service-m5fybvnr    
  ECS_CLUSTER: able-flamingo-sp803j            
  ECS_CONTAINER_NAME: 304619557163.dkr.ecr.ap-southeast-2.amazonaws.com/travel-backend
  ECS_TASK_DEFINITION: .github/ecs/task-definition.json
                                             
permissions:
  contents: write
  packages: write

jobs:
  build-and-verify:
    runs-on: ubuntu-latest
    environment: prod

    services:
      mongo: 
        image: mongo:6
        ports:
          - 27017:27017

    steps:
      # ------------ GIT + NODE ------------ 
      - name: Checkout repository
        uses: actions/checkout@v4
        with: 
            fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v6
        with: 
          node-version: 24

      - name: Install dependencies
        run: npm ci
      
      # ------------ TESTING ------------ 
      - name: Run tests
        run: npm test

      - name: Creating blank .env file
        run: touch .env  
      
      # ------------ DOCKER COMPOSE TEST PHASE ------------ 

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3  

      - name: Build and start services for verification
        run:  docker compose -f Docker-compose.yaml up -d --build

      - name: Stop Docker services after verification
        run: docker compose -f Docker-compose.yaml down
      
  tag-and-publish:
    needs: build-and-verify
    runs-on: ubuntu-latest
    environment: prod
    outputs:
      IMAGE_TAG: ${{ steps.set_image.outputs.image_tag }}
      GHCR_IMAGE: ${{ steps.set_image.outputs.ghcr_image }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with: 
            fetch-depth: 0

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3  
      
      # ------------ LOWERCASE FOR DOCKER TAGS ------------ 
      - name: Set lowercase repository name
        run: |
          echo "OWNER_LC=${OWNER,,}" >> $GITHUB_ENV
          echo "REPO_LC=${REPO,,}" >> $GITHUB_ENV
        env:
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.repository }}

      # ------------ VERSION TAGGING ------------ 
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: "travelApp-v"
          release_branches: release
          default_bump: patch
          dry_run: false
      
      # ------------ SET IMAGE VARIABLES ------------ 
      - name: Set image variables
        id: set_image
        run: |
          IMAGE_TAG="${{ steps.tag_version.outputs.new_tag }}"
          OWNER_LC="${GITHUB_REPOSITORY_OWNER,,}"

          GHCR_IMAGE="ghcr.io/${OWNER_LC}/travelapp-backend:${IMAGE_TAG}"
          GHCR_LATEST="ghcr.io/${OWNER_LC}/travelapp-backend:latest"

          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
          echo "ghcr_image=$GHCR_IMAGE" >> $GITHUB_OUTPUT
          echo "ghcr_latest=$GHCR_LATEST" >> $GITHUB_OUTPUT

      # ------------ LOGIN TO GHCR ------------ 
      - name: Login to Docker Hub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ------------ BUILDX PRODUCTION IMAGE ------------ 
      - name: Build and push production image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            ${{ steps.set_image.outputs.ghcr_image }}
            ${{ steps.set_image.outputs.ghcr_latest }} 
             

      # ------------ CREATE GITHUB RELEASE ------------ 
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
      
  #deploy:
  # needs: tag-and-publish
  # runs-on: ubuntu-latest
  # environment: prod

  #  steps:
  #    - name: Deploy to Render
  #      run: curl -f ${{ secrets.RENDER_DEPLOY_HOOK }}
          

  deploy:
    name: Deploy to Amazon ECS
    runs-on: ubuntu-latest
    needs: tag-and-publish
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }} 

      # ------------ LOWERCASE FOR DOCKER TAGS ------------ 
      - name: Set lowercase repository name
        run: |
          echo "OWNER_LC=${OWNER,,}" >> $GITHUB_ENV
          echo "REPO_LC=${REPO,,}" >> $GITHUB_ENV
        env:
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.repository }}

      # ------------ LOGIN TO GHCR & ECR ------------ 
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # ------------ DEFINE ECR IMAGE ------------ 
      - name: Set ECR image
        id: set-ecr
        run: |
          IMAGE_TAG="${{ needs.tag-and-publish.outputs.IMAGE_TAG }}"
          ECR_IMAGE="${{ steps.login-ecr.outputs.registry }}/travel-backend:${IMAGE_TAG}"
          echo "ecr_image=$ECR_IMAGE" >> $GITHUB_OUTPUT

      # ------------ PULL GHCR IMAGE AND PUSH TO ECR ------------ 
      - name: Pull GHCR and push to ECR
        run: |
          GHCR_IMAGE="${{ needs.tag-and-publish.outputs.GHCR_IMAGE }}"
          ECR_IMAGE="${{ steps.set-ecr.outputs.ecr_image }}"

          docker pull "${GHCR_IMAGE}"
          docker tag "${GHCR_IMAGE}" "$ECR_IMAGE"
          docker push "$ECR_IMAGE"

      # ------------ RENDER ECS TASK ------------
      - name: Render ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: .github/ecs/task-definition.json
          container-name: ${{ env.ECS_CONTAINER_NAME }}
          image: ${{ steps.set-ecr.outputs.ecr_image }}

      # ------------ DEPLOY TO ECS ------------
      - name: Deploy to ECS 
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
        