name: travelApp-project-backend

on: [push]

jobs:
  travelApp-project-backend:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Coder Academy is here!"
          echo "Coder Academy is super cool!"
      - run: echo "You've learned so much if you've already reached this point in the course! You're amazing!"